seed: 123
device: auto

total_timesteps: 200000
log_dir: runs/stage3
checkpoints_dir: checkpoints/stage3
eval_dir: evals/stage3
checkpoint_freq: 10000
eval_freq: 5000
n_eval_episodes: 5
pretrained_path: evals/stage2/best_model.zip

policy_kwargs:
  net_arch: [256, 256]

sac:
  learning_rate: 0.0003
  buffer_size: 1000000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  learning_starts: 1000
  ent_coef: auto
  target_entropy: auto
